
# Move base node parameters. For full documentation of the parameters in this file, please see
#
#  http://www.ros.org/wiki/move_base
#
shutdown_costmaps: false

controller_frequency: 5.0
controller_patience: 3.0


planner_frequency: 1.0
planner_patience: 5.0

oscillation_timeout: 10.0
oscillation_distance: 0.2

# local planner - default is trajectory rollout
# base_local_planner: "teb_local_planner/TebLocalPlannerROS" 
# base_local_planner: "eband_local_planner/EBandPlannerROS" 
# base_local_planner: "dwa_local_planner/DWAPlannerROS"

base_global_planner: "navfn/NavfnROS" #alternatives: global_planner/GlobalP

global_costmap:
  global_frame: map
  robot_base_frame: chassis0
  update_frequency: 20
  static_map: true
  robot_radius: 0.0
  inflation_radius: 0.30
  transform_tolerance: 0.5

local_costmap:
  global_frame: map
  robot_base_frame: chassis0
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05
  transform_tolerance: 0.5
  obstacle_layer:
    enabled:              true
    max_obstacle_height:  2
    origin_z:             0.0 
    z_resolution:         0.2
    z_voxels:             2
    unknown_threshold:    15
    mark_threshold:       0
    combination_method:   1
    track_unknown_space:  true    #true needed for disabling global path planning through unknown space

    publish_voxel_map: false
    observation_sources:  scan
    scan:
      data_type: LaserScan
      topic: visionbot/laser/scan
      marking: true
      clearing: true
      min_obstacle_height: 0
      max_obstacle_height: 2